[package]
name = "star-shot"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.28"
c_str_macro = "1.0.3"
cgmath = "0.18.0"
gl = "0.14.0"
image = "0.25.2"
imageproc = "0.25.0"
rand = "0.8.5"
sdl2 = { version = "0.37.0", default-features = false, features = ["mixer"] }
